### ISSUE TITLE
[ADE ImportError: Can't load waagent

### ISSUE THREAD

**Issue by johanburati** [Azure/azure-linux-extensions#1216]
```
[ExtensionOperationError] Non-zero exit code: 1, /var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.52/extension_shim.sh -c main/handle.py --install
[stdout]
Python 2.7.17
Traceback (most recent call last):
  File "main/handle.py", line 32, in <module>
    from Utils import HandlerUtil
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.52/main/Utils/HandlerUtil.py", line 71, in <module>
    from Utils.WAAgentUtil import waagent
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.52/main/Utils/WAAgentUtil.py", line 41, in <module>
    waagent = imp.load_source('waagent', agentPath)
  File "/usr/sbin/waagent", line 46, in <module>
    raise ImportError("Can't load waagent")
ImportError: Can't load waagent
```

**Comment by rajeshbshinde** [comment]
I am also facing same issue.

mporting utils failed with error: Can't load waagent
Unable to initialize waagent log because of exception global name 'waagent' is not defined
