### ISSUE TITLE
[ADE] Failed to enable the extension with error: No module named parted,

### ISSUE THREAD

**Issue by adamlepkowski** [Azure/azure-linux-extensions#1247]
Hi, I'm unable to intialize ADE for linux machine (Ubuntu 18.04). Any ideas how to solve it?

`PS /home/> az vm encryption enable --disk-encryption-keyvault {kv_name} --name {vm_name} --resource-group {rg_name} --volume-type ALL
`
Exception:

> Deployment failed. Correlation ID: b65ca250-bf9d-4c72-8456-08ec64c8efbd. VM has reported a failure when processing extension 'AzureDiskEncryptionForLinux'. 
> Error message: "Failed to enable the extension with error: No module named parted, stack trace: Traceback (most recent call last):
>   File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.2.0.72/main/handle.py", line 2209, in daemon
>     daemon_encrypt()
>   File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.2.0.72/main/handle.py", line 1940, in daemon_encrypt
>     from oscrypto.ubuntu_1604 import Ubuntu1604EncryptionStateMachine
>   File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.2.0.72/main/oscrypto/ubuntu_1604/__init__.py", line 16, in <module>
>     from .Ubuntu1604EncryptionStateMachine import *
>   File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.2.0.72/main/oscrypto/ubuntu_1604/Ubuntu1604EncryptionStateMachine.py", line 37, in <module>
>     from .encryptstates import *
>   File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.2.0.72/main/oscrypto/ubuntu_1604/encryptstates/__init__.py", line 33, in <module>
>     from .SplitRootPartitionState import *
>   File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.2.0.72/main/oscrypto/ubuntu_1604/encryptstates/SplitRootPartitionState.py", line 26, in <module>
>     import parted
> ImportError: No module named parted
> "

**Comment by antanof** [comment]
A similar error with NSG activated :
```
Error: Code="VMExtensionProvisioningError" Message="VM has reported a failure when processing extension 'DiskEncryption'. Error message: \"Failed to enable the extension with error: No module named six, stack trace: Traceback (most recent call last):\n  File \"/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.52/main/handle.py\", line 2196, in daemon\n    daemon_encrypt()\n  File \"/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.52/main/handle.py\", line 1927, in daemon_encrypt\n    from oscrypto.ubuntu_1604 import Ubuntu1604EncryptionStateMachine\n  File \"/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.52/main/oscrypto/__init__.py\", line 17, in <module>\n    from OSEncryptionStateMachine import *\n  File \"/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.52/main/oscrypto/OSEncryptionStateMachine.py\", line 48, in <module>\n    from transitions import *\n  File \"/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.52/transitions/transitions/__init__.py\", line 2, in <module>\n    from .core import (State, Transition, Event, EventData, Machine, MachineError,\n  File \"/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.52/transitions/transitions/core.py\", line 8, in <module>\n    from six import string_types\nImportError: No module named six\n\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot "

  on main.tf line 274, in resource "azurerm_virtual_machine_extension" "disk-lin-encryption":
 274: resource "azurerm_virtual_machine_extension" "disk-lin-encryption"
```
In addition I set up the outbound with the azureKeyVault tag service...

**Comment by mikemowgli** [comment]
I had the same problem. Adding "apt-get install python-parted" in my init script (or anywhere as long as it's installed) fixed it for me.
I tried installing the module with pip but that failed.

**Comment by antanof** [comment]
On the NSG for inbound :
```
security_rule {
  priority                    = "302"
  direction                   = "Inbound"
  name                        = "allow_sub_vault_to_subnet"
  source_port_range           = "*"
  destination_port_range      = "*"
  protocol                    = "*"
  source_address_prefix       = module.vault.vault_private_ip
  destination_address_prefix  = var.subnet_iprange[0]
  access                      = "Allow"
}

security_rule {
  priority                    = "303"
  direction                   = "Inbound"
  name                        = "allow_vaultservice_to_subnet"
  source_port_range           = "*"
  destination_port_range      = "*"
  protocol                    = "*"
  source_address_prefix       = "AzureKeyVault"
  destination_address_prefix  = var.subnet_iprange[0]
  access                      = "Allow"
}

security_rule {
  priority                    = "304"
  direction                   = "Inbound"
  name                        = "allow_AD_to_subnet"
  source_port_range           = "*"
  destination_port_range      = "*"
  protocol                    = "*"
  source_address_prefix       = "AzureActiveDirectory"
  destination_address_prefix  = var.subnet_iprange[0]
  access                      = "Allow"
}
```
For Outbound :
```
security_rule {
    priority                    = "400"
    direction                   = "Outbound"
    name                        = "allow_vault_from_subnet"
    source_port_range           = "*"
    destination_port_range      = "*"
    protocol                    = "*"
    source_address_prefix       = var.subnet_iprange[0]
    destination_address_prefix  = "AzureKeyVault"
    access                      = "Allow"
  }

  security_rule {
    priority                    = "500"
    direction                   = "Outbound"
    name                        = "allow_ip_vault_from_subnet"
    source_port_range           = "*"
    destination_port_range      = "*"
    protocol                    = "*"
    source_address_prefix       = var.subnet_iprange[0]
    destination_address_prefix  = module.vault.vault_private_ip
    access                      = "Allow"
  }

  security_rule {
    priority                    = "600"
    direction                   = "Outbound"
    name                        = "allow_AD_from_subnet"
    source_port_range           = "*"
    destination_port_range      = "*"
    protocol                    = "*"
    source_address_prefix       = var.subnet_iprange[0]
    destination_address_prefix  = "AzureActiveDirectory"
    access                      = "Allow"
  }
```

But after lot of network problems with UDR -> 0.0.0.0/0 on firewall VirtualAppliance and Firewall-s network rules and application collection rules. You have to authorize all specifics azure services in your firewall : DNS, AD, KeyVault…
