### ISSUE TITLE
Azure Disc Encryption fails for added discs on Ubuntu 20.04 VM

### ISSUE THREAD

**Issue by sfehrmann** [Azure/azure-linux-extensions#1485]
Hi, on our VM I realized I needed bigger `/home` and `/var` directories to prevent users from crashing the server. The server was setup with an full ADE encryption, then I added two more disks and mounted them in `/home` and `/var`. Filesystem on all discs is XFS. 

I tried to add the two discs via 
```shell
az vm encryption enable --resource-group MyResourceGroup --name myVm --disk-encryption-keyvault myKeyVault --key-encryption-key myKekKey --key-encryption-keyvault myKekKeyVault  --debug --output yamlc --volume-type ALL
```
This failed and I lost access to the server, then I removed  
```shell
az vm encryption disable  --resource-group MyResourceGroup  --name myVm  --volume-type "All"
```

I regained SSH access to the server, OS disc remained encrypted, three data discs report now status unencrypted. So I retried above `az vm encryption enable` command and now face the following error

```
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/--SUBSCRIPTION--/providers/Microsoft.Compute/locations/westeurope/operations/URL&api-version=2021-07-01 HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies:     'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-resource': 'Microsoft.Compute/GetOperation3Min;14997,Microsoft.Compute/GetOperation30Min;29967'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '----'
cli.azure.cli.core.sdk.policies:     'Server': 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-reads': '11994'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '----'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': '----'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'Date': 'Mon, 31 Jan 2022 15:53:20 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {
  "startTime": "2022-01-31T15:51:49.6094935+00:00",
  "endTime": "2022-01-31T15:53:14.203853+00:00",
  "status": "Failed",
  "error": {
    "code": "VMExtensionProvisioningError",
    "message": "VM has reported a failure when processing extension 'AzureDiskEncryptionForLinux'. Error message: \"Failed to encrypt data volumes with error: Encryption failed for name:sdc1 type:part fstype:xfs mountpoint:/mnt/datadrive label: model: size:1099509530624 majmin:8:33 device_id:---ID---, stack trace: Traceback (most recent call last):\n  File \"/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.2.0.90/main/handle.py\", line 1839, in daemon_encrypt\n    while not daemon_encrypt_data_volumes(encryption_marker=encryption_marker,\n  File \"/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.2.0.90/main/handle.py\", line 2097, in daemon_encrypt_data_volumes\n    raise Exception(message)\nException: Encryption failed for name:sdc1 type:part fstype:xfs mountpoint:/mnt/datadrive label: model: size:1099509530624 majmin:8:33 device_id:---ID---\n\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionADELinuxTroubleshoot "
  },
  "name": "23e37bcf-a568-43b6-9d61-e3ef6b05702d"
}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 483, in run
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 522, in _poll
azure.core.polling.base_polling.OperationFailed: Operation failed or canceled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/vm/disk_encryption.py", line 161, in encrypt_vm
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 1008, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 995, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/_poller.py", line 255, in result
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/_poller.py", line 275, in wait
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/_poller.py", line 192, in _start
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 501, in run
azure.core.exceptions.HttpResponseError: (VMExtensionProvisioningError) VM has reported a failure when processing extension 'AzureDiskEncryptionForLinux'. Error message: "Failed to encrypt data volumes with error: Encryption failed for name:sdc1 type:part fstype:xfs mountpo  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.2.0.90/main/handle.py", line 1839, in daemon_encrypt
    while not daemon_encrypt_data_volumes(encryption_marker=encryption_marker,
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.2.0.90/main/handle.py", line 2097, in daemon_encrypt_data_volumes
    raise Exception(message)
Exception: Encryption failed for name:sdc1 type:part fstype:xfs mountpoint:/mnt/datadrive label: model: size:1099509530624 majmin:8:33 device_id:---ID---
"

More information on troubleshooting is available at https://aka.ms/VMExtensionADELinuxTroubleshoot
Code: VMExtensionProvisioningError
 device_id:---ID---, stack trace: Traceback (most recent call last):
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.2.0.90/main/handle.py", line 1839, in daemon_encrypt
    while not daemon_encrypt_data_volumes(encryption_marker=encryption_marker,
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.2.0.90/main/handle.py", line 2097, in daemon_encrypt_data_volumes
    raise Exception(message)
Exception: Encryption failed for name:sdc1 type:part fstype:xfs mountpoint:/mnt/datadrive label: model: size:1099509530624 majmin:8:33 device_id:---ID---
"
More information on troubleshooting is available at https://aka.ms/VMExtensionADELinuxTroubleshoot

cli.azure.cli.core.azclierror: (VMExtensionProvisioningError) VM has reported a failure when processing extension 'AzureDiskEncryptionForLinux'. Error message: "Failed to encrypt data volumes with error: Encryption failed for name:sdc1 type:part fstype:xfs mountpoint:/mnt/datadrive label: model: size:1099509530624 majmin:8:33 device_id:---ID---, stack trace: Traceback (most recent call last):
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.2.0.90/main/handle.py", line 1839, in daemon_encrypt
    while not daemon_encrypt_data_volumes(encryption_marker=encryption_marker,
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.2.0.90/main/handle.py", line 2097, in daemon_encrypt_data_volumes
    raise Exception(message)
Exception: Encryption failed for name:sdc1 type:part fstype:xfs mountpoint:/mnt/datadrive label: model: size:1099509530624 majmin:8:33 device_id:---ID---
"

More information on troubleshooting is available at https://aka.ms/VMExtensionADELinuxTroubleshoot
Code: VMExtensionProvisioningError
Message: VM has reported a failure when processing extension 'AzureDiskEncryptionForLinux'. Error message: "Failed to encrypt data volumes with error: Encryption failed for name:sdc1 type:part fstype:xfs mountpoint:/mnt/datadrive label: model: size:1099509530624 majmin:8:33 device_id:---ID---, stack trace: Traceback (most recent call last):
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.2.0.90/main/handle.py", line 1839, in daemon_encrypt
    while not daemon_encrypt_data_volumes(encryption_marker=encryption_marker,
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.2.0.90/main/handle.py", line 2097, in daemon_encrypt_data_volumes
    raise Exception(message)
Exception: Encryption failed for name:sdc1 type:part fstype:xfs mountpoint:/mnt/datadrive label: model: size:1099509530624 majmin:8:33 device_id:---ID---
"

More information on troubleshooting is available at https://aka.ms/VMExtensionADELinuxTroubleshoot
az_command_data_logger: (VMExtensionProvisioningError) VM has reported a failure when processing extension 'AzureDiskEncryptionForLinux'. Error message: "Failed to encrypt data volumes with error: Encryption failed for name:sdc1 type:part fstype:xfs mountpoint:/mnt/datadrive label: model: size:1099509530624 majmin:8:33 device_id:---ID---, stack trace: Traceback (most recent call last):
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.2.0.90/main/handle.py", line 1839, in daemon_encrypt
    while not daemon_encrypt_data_volumes(encryption_marker=encryption_marker,
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.2.0.90/main/handle.py", line 2097, in daemon_encrypt_data_volumes
    raise Exception(message)
Exception: Encryption failed for name:sdc1 type:part fstype:xfs mountpoint:/mnt/datadrive label: model: size:1099509530624 majmin:8:33 device_id:---ID---
"

More information on troubleshooting is available at https://aka.ms/VMExtensionADELinuxTroubleshoot
Code: VMExtensionProvisioningError
Message: VM has reported a failure when processing extension 'AzureDiskEncryptionForLinux'. Error message: "Failed to encrypt data volumes with error: Encryption failed for name:sdc1 type:part fstype:xfs mountpoint:/mnt/datadrive label: model: size:1099509530624 majmin:8:33 device_id:---ID---, stack trace: Traceback (most recent call last):
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.2.0.90/main/handle.py", line 1839, in daemon_encrypt
    while not daemon_encrypt_data_volumes(encryption_marker=encryption_marker,
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.2.0.90/main/handle.py", line 2097, in daemon_encrypt_data_volumes
    raise Exception(message)
Exception: Encryption failed for name:sdc1 type:part fstype:xfs mountpoint:/mnt/datadrive label: model: size:1099509530624 majmin:8:33 device_id:---ID---
"

More information on troubleshooting is available at https://aka.ms/VMExtensionADELinuxTroubleshoot
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03DD78E0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 93.533 seconds (init: 0.152, invoke: 93.381)
telemetry.save: Save telemetry record of length 5304 in cache
telemetry.check: Negative: The C:\Users\USERNAME\.azure\telemetry.txt was modified at 2022-01-31 16:47:07.949019, which in less than 600.000000 s
cli.azure.cli.core.auth.identity: _dump_msal_http_cache: C:\Users\USERNAME\.azure\msal_http_cache.bin
```

Is there a workaround to fix this? The data disc that now fails was encrypted previously.

**Comment by sfehrmann** [comment]
This probably failed as I attached the disks too early into system directories and the system was not able to unmount the disks. In case this is the problem, including this in the warning would have been helpful.

On a different server, the encryption succeeded when mounting an additional disk to some random `/datadisk_x` directory. Though the disk is not added to crypttab or fstab, so my take away is that a configuration change after the initial setup is tricky.
