### ISSUE TITLE
[CustomScript] blob urls with implicit $root container do not work

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-linux-extensions#190]
`http://acct.blob.core.windows.net/f.txt` is actually a valid blob URL with implicit container name `$root` however the parsing logic in `get_properties_from_uri` does not actually support this. Not a blocking bug as users can always specify URLs with `$root/f.txt` explicitly.

```py
>>> get_properties_from_uri('http://acct.blob.core.windows.net/f.txt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 9, in get_properties_from_uri
Exception: Failed to extract container, blob, from f.txt
```

**Comment by ahmetalpbalkan** [comment]
This is fixed in the rewrite. We handle this special case and have tests about this.
