### ISSUE TITLE
[OSPatching] Oracle 7.2 enable fails

### ISSUE THREAD

**Issue by hglkrijger** [Azure/azure-linux-extensions#196]
With agent rc3 bits, the enable step fails with:

2016/07/06 17:02:08 ERROR:Reading from file /etc/crontab Exception is [Errno 2] No such file or directory: '/etc/crontab'
2016/07/06 17:02:08 ERROR:[Microsoft.OSTCExtensions.OSPatchingForLinux-1.0]Failed to enable the extension with error: 'NoneType' object has no attribute 'split', stack trace: Traceback (most recent call last):
2016/07/06 17:02:08 ERROR:  File "/var/lib/waagent/Microsoft.OSTCExtensions.OSPatchingForLinux-2.3.0.1/./handler.py", line 74, in enable
2016/07/06 17:02:08 ERROR:    MyPatching.enable()
2016/07/06 17:02:08 ERROR:  File "/var/lib/waagent/Microsoft.OSTCExtensions.OSPatchingForLinux-2.3.0.1/patch/AbstractPatching.py", line 323, in enable
2016/07/06 17:02:08 ERROR:    self.set_download_cron()
2016/07/06 17:02:08 ERROR:  File "/var/lib/waagent/Microsoft.OSTCExtensions.OSPatchingForLinux-2.3.0.1/patch/AbstractPatching.py", line 368, in set_download_cron
2016/07/06 17:02:08 ERROR:    waagent.ReplaceFileContentsAtomic(self.crontab, '\n'.join(filter(lambda a: a and (old_line_end not in a), waagent.GetFileContents(self.crontab).split('\n'))) + new_line)
2016/07/06 17:02:08 ERROR:AttributeError: 'NoneType' object has no attribute 'split'
2016/07/06 17:02:08 ERROR:
2016/07/06 17:02:08 [Microsoft.OSTCExtensions.OSPatchingForLinux-1.0]Enable,error,0,Enable Failed. Current Configuation: category=important,dayOfWeek=Everyday,distUpgradeAll=False,intervalOfWeeks=1,stop=False,disabled=False,installDuration=01:00,rebootAfterPatch=rebootifneed,oneoff=False,startTime=03:00

[root@o72rc3 waagent]# ls /etc/cr*
/etc/crypttab

/etc/cron.daily:
0yum-daily.cron  logrotate  man-db.cron

/etc/cron.hourly:
0yum-hourly.cron

**Comment by mbearup** [comment]
The failure occurs because the cronie package is not included in the latest Oracle 7.2 image. Confirmed with Oracle that this is intentional, as they're moving towards a slim, container-focused build. Despite that, Oracle will add cronie into the next 7.2 image release. I will close this but when compatibility is retored.
