### ISSUE TITLE
[VMAccess] No such file or directory: '/var/lib/waagent/ovf-env.xml'

### ISSUE THREAD

**Issue by saimsh** [Azure/azure-linux-extensions#204]
OS : CEntoOS6.4
downloaded from : https://sourceforge.net/projects/elastix/files/Elastix%20PBX%20Appliance%20Software/3.0.0/

Prepared a CentOS-based virtual machine for Azure:
https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-create-upload-centos/

python version : Python 2.6.6
waagent version : 2.0.18

```
/var/log/waagent.log:
2016/07/19 22:35:04 Found Plugin: Microsoft.OSTCExtensions.VMAccessForLinux version: 1.4.0.0
2016/07/19 22:35:04 Downloading plugin manifest: Microsoft.OSTCExtensions.VMAccessForLinux from https://rdfepirv2dm1prdstr01.blob.core.windows.net/b01058962be54ceca550a390fa5ff064/Microsoft.OSTCExtensions_VMAccessForLinux_uscentral_manifest.xml
2016/07/19 22:35:04 Plugin server is: rdfepirv2dm1prdstr01.blob.core.windows.net
2016/07/19 22:35:04 Bundle URI = http://rdfepirv2dm1prdstr01.blob.core.windows.net/b01058962be54ceca550a390fa5ff064/Microsoft.OSTCExtensions__VMAccessForLinux__1.4.0.0
2016/07/19 22:35:04 Plugin bundlehttp://rdfepirv2dm1prdstr01.blob.core.windows.net/b01058962be54ceca550a390fa5ff064/Microsoft.OSTCExtensions__VMAccessForLinux__1.4.0.0downloaded successfully length = 83841
2016/07/19 22:35:04 Extracted http://rdfepirv2dm1prdstr01.blob.core.windows.net/b01058962be54ceca550a390fa5ff064/Microsoft.OSTCExtensions__VMAccessForLinux__1.4.0.0 to /var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.0.0
2016/07/19 22:35:04 Found RuntimeSettings for Microsoft.OSTCExtensions.VMAccessForLinux V 1.4.0.0
2016/07/19 22:35:04 SetHandlerState: Microsoft.OSTCExtensions.VMAccessForLinux-1.4.0.0, NotInstalled
2016/07/19 22:35:04 Spawned ./vmaccess.py -install PID 3240
2016/07/19 22:35:04 VMAccess started to handle.
2016/07/19 22:35:04 [VMAccess-0.0]cwd is /var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.0.0
2016/07/19 22:35:04 [Microsoft.OSTCExtensions.VMAccessForLinux-1.0]Change log file to /var/log/azure/Microsoft.OSTCExtensions.VMAccessForLinux/1.4.0.0/extension.log
2016/07/19 22:35:09 installCommand completed.
2016/07/19 22:35:09 SetHandlerState: Microsoft.OSTCExtensions.VMAccessForLinux-1.4.0.0, Installed
2016/07/19 22:35:09 Installation completed for Microsoft.OSTCExtensions.VMAccessForLinux-1.4.0.0
2016/07/19 22:35:09 Found RuntimeSettings for Microsoft.OSTCExtensions.VMAccessForLinux V 1.4.0.0
2016/07/19 22:35:09 Spawned ./vmaccess.py -enable PID 3246
2016/07/19 22:35:09 VMAccess started to handle.
2016/07/19 22:35:09 [VMAccess-0.0]cwd is /var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.0.0
2016/07/19 22:35:09 [Microsoft.OSTCExtensions.VMAccessForLinux-1.0]Change log file to /var/log/azure/Microsoft.OSTCExtensions.VMAccessForLinux/1.4.0.0/extension.log
2016/07/19 22:35:14 ERROR:Process 3246 returned non-zero exit code(1)
2016/07/19 22:35:14 SetHandlerState: Microsoft.OSTCExtensions.VMAccessForLinux-1.4.0.0, Installed
2016/07/19 22:35:14 ERROR:Enable failed for Microsoft.OSTCExtensions.VMAccessForLinux-1.4.0.0
2016/07/19 22:35:14 Processing completed for Microsoft.OSTCExtensions.VMAccessForLinux-1.4.0.0
2016/07/19 22:35:14 Finished processing ExtensionsConfig.xml
2016/07/19 22:35:14 Successfully reported handler status
```

```
=================================
/var/log/azure/extension.log error:
2016/07/19 22:35:09 [Microsoft.OSTCExtensions.VMAccessForLinux-1.0]set most recent sequence number to 0
2016/07/19 22:35:09 ERROR:Reading from file /var/lib/waagent/ovf-env.xml Exception is [Errno 2] No such file or directory: '/var/lib/waagent/ovf-env.xml'
2016/07/19 22:35:09 ERROR:[Microsoft.OSTCExtensions.VMAccessForLinux-1.0]Failed to enable the extension with error: expected string or buffer, stack trace: Traceback (most recent call last):
2016/07/19 22:35:09 ERROR:  File "/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.0.0/./vmaccess.py", line 96, in enable
2016/07/19 22:35:09 ERROR:    _set_user_account_pub_key(protect_settings, hutil)
2016/07/19 22:35:09 ERROR:  File "/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.0.0/./vmaccess.py", line 140, in _set_user_account_pub_key
2016/07/19 22:35:09 ERROR:    ovf_env = waagent.OvfEnv().Parse(ovf_xml)
2016/07/19 22:35:09 ERROR:  File "/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.0.0/waagent", line 4382, in Parse
2016/07/19 22:35:09 ERROR:    LogIfVerbose(re.sub("<UserPassword>.*?<", "<UserPassword>*<", xmlText))
2016/07/19 22:35:09 ERROR:  File "/usr/lib64/python2.6/re.py", line 151, in sub
2016/07/19 22:35:09 ERROR:    return _compile(pattern, 0).sub(repl, string, count)
2016/07/19 22:35:09 ERROR:TypeError: expected string or buffer
2016/07/19 22:35:09 ERROR:
2016/07/19 22:35:09 [Microsoft.OSTCExtensions.VMAccessForLinux-1.0]Enable,error,0,Enable failed.
=================
```

```
/var/log/azure/commandexecution.log
2016/07/19 22:35:04 Downloading plugin manifest: Microsoft.OSTCExtensions.VMAccessForLinux from https://rdfepirv2dm1prdstr01.blob.core.windows.net/b01058962be54ceca550a390fa5ff064/Microsoft.OSTCExtensions_VMAccessForLinux_uscentral_manifest.xml
2016/07/19 22:35:04 Plugin server is: rdfepirv2dm1prdstr01.blob.core.windows.net
2016/07/19 22:35:04 Bundle URI = http://rdfepirv2dm1prdstr01.blob.core.windows.net/b01058962be54ceca550a390fa5ff064/Microsoft.OSTCExtensions__VMAccessForLinux__1.4.0.0
2016/07/19 22:35:04 Plugin bundlehttp://rdfepirv2dm1prdstr01.blob.core.windows.net/b01058962be54ceca550a390fa5ff064/Microsoft.OSTCExtensions__VMAccessForLinux__1.4.0.0downloaded successfully length = 83841
2016/07/19 22:35:04 Extracted http://rdfepirv2dm1prdstr01.blob.core.windows.net/b01058962be54ceca550a390fa5ff064/Microsoft.OSTCExtensions__VMAccessForLinux__1.4.0.0 to /var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.0.0
2016/07/19 22:35:04 Found RuntimeSettings for Microsoft.OSTCExtensions.VMAccessForLinux V 1.4.0.0
2016/07/19 22:35:04 Spawned ./vmaccess.py -install PID 3240
2016/07/19 22:35:09 installCommand completed.
2016/07/19 22:35:09 Installation completed for Microsoft.OSTCExtensions.VMAccessForLinux-1.4.0.0
2016/07/19 22:35:09 Found RuntimeSettings for Microsoft.OSTCExtensions.VMAccessForLinux V 1.4.0.0
2016/07/19 22:35:09 Spawned ./vmaccess.py -enable PID 3246
2016/07/19 22:35:14 Process 3246 returned non-zero exit code(1)
2016/07/19 22:35:14 Enable failed for Microsoft.OSTCExtensions.VMAccessForLinux-1.4.0.0
2016/07/19 22:35:14 Processing completed for Microsoft.OSTCExtensions.VMAccessForLinux-1.4.0.0
2016/07/19 22:35:14 Finished processing ExtensionsConfig.xml
```

**Comment by boumenot** [comment]
The base OS may be CentOS, but this appears to be an appliance.  Appliances are not supported, but patches are welcome.  Please correct my understanding.

**Comment by saimsh** [comment]
Yes, it is true. the is an appliance. I can definitely convey the info about the supportability. However, i think i can repro the issue with gallery images as well. I will update once i am able to repro. :)
Thanks for the prompt response.

**Comment by boumenot** [comment]
Great!  Let us know.

**Comment by boumenot** [comment]
I recently updated VMAccess to 1.4.1.0 to address install issues.  Would you please retry with this version, and report back.

**Comment by saimsh** [comment]
Thank you Christopher. I will repro the scenario, test it and provide update to the soonest possible.
Again, thanks for looking into it.
Cheers!
Saim

**Comment by boumenot** [comment]
Closed due to lack of activity.  Please re-open as appropriate.

**Comment by saimsh** [comment]
apologies. I had not been able to test this yet. I will reopen if the issue is still reproducible with the new extension update

**Comment by omusil24** [comment]
I have the same problem with version 1.4.7.1.

OS: CentOS 7.4 with latest packages as of today (2018/03/12)

/var/log/waagent.log:
```
2018/03/12 16:24:02.834830 INFO [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1] Target handler state: enabled
2018/03/12 16:24:02.850763 INFO [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1] [Enable] current handler state is: notinstalled
2018/03/12 16:24:03.014274 INFO Event: name=Microsoft.OSTCExtensions.VMAccessForLinux, op=Download, message=Download succeeded, duration=153
2018/03/12 16:24:03.024684 INFO [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1] Initialize extension directory
2018/03/12 16:24:03.036990 INFO [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1] Update settings file: 0.settings
2018/03/12 16:24:03.040661 INFO [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1] Install extension [./vmaccess.py -install]
2018/03/12 16:24:03 VMAccess started to handle.
2018/03/12 16:24:03 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1] cwd is /var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1
2018/03/12 16:24:03 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1] Change log file to /var/log/azure/Microsoft.OSTCExtensions.VMAccessForLinux/1.4.7.1/extension.log
2018/03/12 16:24:04.195538 INFO Event: name=Microsoft.OSTCExtensions.VMAccessForLinux, op=Install, message=Launch command succeeded: ./vmaccess.py -install, duration=1145
2018/03/12 16:24:04.254347 INFO [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1] Enable extension [./vmaccess.py -enable]
2018/03/12 16:24:04 VMAccess started to handle.
2018/03/12 16:24:04 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1] cwd is /var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1
2018/03/12 16:24:04 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1] Change log file to /var/log/azure/Microsoft.OSTCExtensions.VMAccessForLinux/1.4.7.1/extension.log
2018/03/12 16:24:05.298024 ERROR Event: name=Microsoft.OSTCExtensions.VMAccessForLinux, op=Enable, message=[ExtensionError] Non-zero exit code: 1, ./vmaccess.py -enable, duration=0
2018/03/12 16:24:05.459902 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=Incarnation 2, duration=2818
```

/var/log/azure/Microsoft.OSTCExtensions.VMAccessForLinux/1.4.7.1/extension.log:
```
2018/03/12 16:24:04 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1] Config decoded correctly.
2018/03/12 16:24:04 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1] set most recent sequence number to 0
2018/03/12 16:24:04 ERROR:Reading from file /var/lib/waagent/ovf-env.xml Exception is [Errno 2] No such file or directory: '/var/lib/waagent/ovf-env.xml'
2018/03/12 16:24:04 ERROR:[Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1] Failed to enable the extension with error: expected string or buffer, stack trace: Traceback (most recent call last):
2018/03/12 16:24:04 ERROR:  File "/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1/./vmaccess.py", line 107, in enable
2018/03/12 16:24:04 ERROR:    _set_user_account_pub_key(protect_settings, hutil)
2018/03/12 16:24:04 ERROR:  File "/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1/./vmaccess.py", line 180, in _set_user_account_pub_key
2018/03/12 16:24:04 ERROR:    ovf_env = waagent.OvfEnv().Parse(ovf_xml)
2018/03/12 16:24:04 ERROR:  File "/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1/waagent", line 4777, in Parse
2018/03/12 16:24:04 ERROR:    LogIfVerbose(re.sub("<UserPassword>.*?<", "<UserPassword>*<", xmlText))
2018/03/12 16:24:04 ERROR:  File "/usr/lib64/python2.7/re.py", line 151, in sub
2018/03/12 16:24:04 ERROR:    return _compile(pattern, flags).sub(repl, string, count)
2018/03/12 16:24:04 ERROR:TypeError: expected string or buffer
2018/03/12 16:24:04 ERROR:
2018/03/12 16:24:04 [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1] Enable,error,0,Enable failed.
```

**Comment by boumenot** [comment]
/var/lib/waagent/ovf-env.xml is created at deployment time, and is expected to exist for the lifetime of the VM.  

Do you know why this file was not created or was deleted?

 1. Was the VM created for an existing VM image on Azure?
 1. Was /var/lib/waagent deleted by the user?
 1. Something else?

**Comment by omusil24** [comment]
I thought it could be caused by a restart so I created a new VM from the same source and it happened again.

1. No, this is a custom VM that is being prepared to be published on Azure.
2. No.
3. No.

But actually I just read the full waagent.log (https://gist.github.com/omusil24/8ab09a6492aa167c80f5b1ff308fd838) and it seems that for some reason the provisioning DVD was not mounted.
