### ISSUE TITLE
"azure vm extension set..." with ssh_key and no password fails with "Enable failed."

### ISSUE THREAD

**Issue by navicore** [Azure/azure-linux-extensions#241]
problem started yesterday.

```
azure vm extension set $rg $vm VMAccessForLinux Microsoft.OSTCExtensions 1.4 --private-config-path "./${user}_protected.json"
```

where json only has "username" and "ssh_key" fails with:

```
verbose: Error: Long running operation failed with error: 'VM has reported a failure when processing extension 'VMAccessForLinux'. Error message: "Enable failed.".'.
  <<< async stack >>>
  at createOrUpdateVMExtension__18 (/Users/esweeney/.nvm/versions/node/v6.3.1/lib/node_modules/azure-cli/lib/commands/arm/vm/virtualMachine.js:252:89)
  at resetVMAccess__16 (/Users/esweeney/.nvm/versions/node/v6.3.1/lib/node_modules/azure-cli/lib/commands/arm/vm/vmClient.js:627:20)
  at __15 (/Users/esweeney/.nvm/versions/node/v6.3.1/lib/node_modules/azure-cli/lib/commands/arm/vm/vm.js:359:16)
  <<< raw stack >>>
    at PollingState.getCloudError (/Users/esweeney/.nvm/versions/node/v6.3.1/lib/node_modules/azure-cli/node_modules/ms-rest-azure/lib/pollingState.js:126:15)
```

problem goes away when a password is added.

**Comment by boumenot** [comment]
Thank you for reporting the issue, and sorry that we broke you.  I've submitted PR #240 to correct this.
