### ISSUE TITLE
VMEncryption error " Cannot read property 'uri' of undefined"

### ISSUE THREAD

**Issue by akramwaseem** [Azure/azure-linux-extensions#517]
error:   Cannot read property 'uri' of undefined
error:   Error information has been recorded to /Users/wmohamme/.azure/azure.err
verbose: TypeError: Cannot read property 'uri' of undefined
  <<< async stack >>>
    at ___ (/usr/local/azure/lib/commands/arm/vm/vmClient.js:1681:64)
    at ___ (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at ___ (/usr/local/azure/lib/commands/arm/vm/virtualMachine.js:63:129)
    at __tryCatch (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/local/azure/lib/commands/arm/vm/virtualMachine.js:63:65)
    at getVM__4 (/usr/local/azure/lib/commands/arm/vm/virtualMachine.js:63:31)
  at createVMBackup__44 (/usr/local/azure/lib/commands/arm/vm/vmClient.js:1674:35)
  at setAzureDiskEncryption__46 (/usr/local/azure/lib/commands/arm/vm/vmClient.js:1846:33)
  at __21 (/usr/local/azure/lib/commands/arm/vm/vm.js:473:16)
  <<< raw stack >>>
    at ___ (/usr/local/azure/lib/commands/arm/vm/vmClient.js:1681:64)
    at ___ (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:111:13)
    at ___ (/usr/local/azure/lib/commands/arm/vm/virtualMachine.js:63:129)
    at __tryCatch (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/local/azure/lib/commands/arm/vm/virtualMachine.js:63:65)
    at __$getVM__4 (/usr/local/azure/lib/commands/arm/vm/virtualMachine.js:63:31)
    at __tryCatch (/usr/local/azure/node_modules/streamline/lib/callbacks/runtime.js:150:4)
    at ___ (/usr/local/azure/lib/commands/arm/vm/virtualMachine.js:61:229)
    at ___ (/usr/local/azure/lib/commands/arm/vm/virtualMachine.js:63:47)
    at __$getVM__4 (/usr/local/azure/lib/commands/arm/vm/virtualMachine.js:61:43)
error:   vm enable-disk-encryption command failed

+++++++++++++++++++
++++++++++++++++++++++++

info:    Executing command vm enable-disk-encryption
verbose: Looking up the VM "testvm"
verbose: Looking up the VM "testvm"
verbose: Installing extension "VMBackupForLinuxExtension", VM: "testvm"
one snapshot with tag 0d28baf5-e3f8-4cb8-b0fc-5e93a2357105 is created for this vm.
This cmdlet prepares the VM and enables encryption which may reboot the machine and takes 10-15 minutes to finish. Please save your work on the VM before confirming. Do you want to continue? [y/n]  y
verbose: Installing extension "AzureDiskEncryptionForLinux", VM: "testvm"
error:   Long running operation failed with error: "VM has reported a failure when processing extension 'AzureDiskEncryptionForLinux'. Error message: "Enable failed.".".
error:   Error information has been recorded to /Users/wmohamme/.azure/azure.err
verbose: Error: Long running operation failed with error: "VM has reported a failure when processing extension 'AzureDiskEncryptionForLinux'. Error message: "Enable failed.".".
  <<< async stack >>>
  at createOrUpdateVMExtension__18 (/usr/local/azure/lib/commands/arm/vm/virtualMachine.js:262:89)
  at setAzureDiskEncryption__46 (/usr/local/azure/lib/commands/arm/vm/vmClient.js:1886:33)
  at __21 (/usr/local/azure/lib/commands/arm/vm/vm.js:473:16)
  <<< raw stack >>>
    at PollingState.getCloudError (/usr/local/azure/node_modules/ms-rest-azure/lib/pollingState.js:127:17)
    at /usr/local/azure/node_modules/ms-rest-azure/lib/azureServiceClient.js:157:38
    at Object.async.whilst (/usr/local/azure/node_modules/ms-rest-azure/node_modules/async/lib/async.js:621:13)
    at /usr/local/azure/node_modules/ms-rest-azure/node_modules/async/lib/async.js:617:23
    at /usr/local/azure/node_modules/ms-rest-azure/lib/azureServiceClient.js:130:20
    at _getStatus (/usr/local/azure/node_modules/ms-rest-azure/lib/azureServiceClient.js:184:5)
    at /usr/local/azure/node_modules/ms-rest-azure/lib/azureServiceClient.js:322:12
    at retryCallback (/usr/local/azure/node_modules/ms-rest/lib/filters/systemErrorRetryPolicyFilter.js:89:9)
    at retryCallback (/usr/local/azure/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:140:9)
    at handleRedirect (/usr/local/azure/node_modules/ms-rest/lib/filters/redirectFilter.js:39:9)
error:   vm enable-disk-encryption command failed

This is what i got , after trying to figure out what went wrong .

**Comment by akramwaseem** [comment]
info:    Executing command vm enable-disk-encryption
verbose: Looking up the VM "testvm"
verbose: Looking up the VM "testvm"
verbose: Installing extension "VMBackupForLinuxExtension", VM: "testvm"
one snapshot with tag 0d28baf5-e3f8-4cb8-b0fc-5e93a2357105 is created for this vm.
This cmdlet prepares the VM and enables encryption which may reboot the machine and takes 10-15 minutes to finish. Please save your work on the VM before confirming. Do you want to continue? [y/n]  y
verbose: Installing extension "AzureDiskEncryptionForLinux", VM: "testvm"
error:   Long running operation failed with error: "VM has reported a failure when processing extension 'AzureDiskEncryptionForLinux'. Error message: "Enable failed.".".
error:   Error information has been recorded to /Users/wmohamme/.azure/azure.err
verbose: Error: Long running operation failed with error: "VM has reported a failure when processing extension 'AzureDiskEncryptionForLinux'. Error message: "Enable failed.".".
  <<< async stack >>>
  at createOrUpdateVMExtension__18 (/usr/local/azure/lib/commands/arm/vm/virtualMachine.js:262:89)
  at setAzureDiskEncryption__46 (/usr/local/azure/lib/commands/arm/vm/vmClient.js:1886:33)
  at __21 (/usr/local/azure/lib/commands/arm/vm/vm.js:473:16)
  <<< raw stack >>>
    at PollingState.getCloudError (/usr/local/azure/node_modules/ms-rest-azure/lib/pollingState.js:127:17)
    at /usr/local/azure/node_modules/ms-rest-azure/lib/azureServiceClient.js:157:38
    at Object.async.whilst (/usr/local/azure/node_modules/ms-rest-azure/node_modules/async/lib/async.js:621:13)
    at /usr/local/azure/node_modules/ms-rest-azure/node_modules/async/lib/async.js:617:23
    at /usr/local/azure/node_modules/ms-rest-azure/lib/azureServiceClient.js:130:20
    at _getStatus (/usr/local/azure/node_modules/ms-rest-azure/lib/azureServiceClient.js:184:5)
    at /usr/local/azure/node_modules/ms-rest-azure/lib/azureServiceClient.js:322:12
    at retryCallback (/usr/local/azure/node_modules/ms-rest/lib/filters/systemErrorRetryPolicyFilter.js:89:9)
    at retryCallback (/usr/local/azure/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:140:9)
    at handleRedirect (/usr/local/azure/node_modules/ms-rest/lib/filters/redirectFilter.js:39:9)
error:   vm enable-disk-encryption command failed


This is what i got , after trying to figure out what went wrong .
