### ISSUE TITLE
CustomScriptForLinux - Support setting environment variables within inline scripts

### ISSUE THREAD

**Issue by jpoon** [Azure/azure-linux-extensions#56]
When trying to set an environment variable through inline script. Example: 

```
    {
      "type": "Microsoft.Compute/virtualMachines/extensions",
      "apiVersion": "2015-06-15",
      ...
      "properties": {
        "publisher": "Microsoft.OSTCExtensions",
        "type": "CustomScriptForLinux",
        "typeHandlerVersion": "1.3",
        "settings": {
          "commandToExecute": "[concat('export ENV_VARIABLE=', parameters('SOME-VALUE'))]"
        }
      }
    }
```

You get this error: 

```
2015/11/24 20:24:23 ERROR:[Microsoft.OSTCExtensions.CustomScriptForLinux-1.0]Failed to launch script with error: [Errno 2] No such file or directory,stacktrace: Traceback (most recent call last):
2015/11/24 20:24:23 ERROR:  File "/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.3.0.1/customscript.py", line 320, in run_script
2015/11/24 20:24:23 ERROR:    stderr=err_out)
2015/11/24 20:24:23 ERROR:  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
2015/11/24 20:24:23 ERROR:    errread, errwrite)
2015/11/24 20:24:23 ERROR:  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
2015/11/24 20:24:23 ERROR:    raise child_exception
2015/11/24 20:24:23 ERROR:OSError: [Errno 2] No such file or directory
2015/11/24 20:24:23 ERROR:
2015/11/24 20:24:23 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.0]Enable,failed,1,Lanch script failed: [Errno 2] No such file or directory
```

And this is because, custom scripts are executed via: 

```
         child = subprocess.Popen(args,
                                 cwd = download_dir,
                                 stdout=std_out,
                                 stderr=err_out)
```
(from https://github.com/Azure/azure-linux-extensions/blob/master/CustomScript/customscript.py - line 315)

Cause the scripts are executed in the context of `Popen`. You can't execute any shell commands such as `export envvar=value`. 

Suggested workarounds:

* Enable shell commands by setting `shell=True` argument on Popen
* Update inline scripts to `bash -c 'export ENV_VARABLE=VALUE'`
* At the very minimum, update documentation

Also, please fix the typo in the error message: `Lanch script failed`

**Comment by bingosummer** [comment]
Thanks @jpoon for your feedback.

* `bash -c 'export ENV_VARABLE=VALUE'` is supported. Does it meet your requirements? Please verify it.
* Will fix the typo.
* Will test the scenario with `shell=True`.

**Comment by EgoAleSum** [comment]
+1 for support for environmental variables. Ideally, it would be nice if we could do something like this in the ARM template:

```json
  {
      "type": "Microsoft.Compute/virtualMachines/extensions",
      "name": "[concat(variables('vm1Name'),'/setupscript')]",
      "apiVersion": "2015-05-01-preview",
      "location": "[resourceGroup().location]",
      "dependsOn": [
        "[concat('Microsoft.Compute/virtualMachines/', variables('vm1Name'))]"
      ],
      "properties": {
        "publisher": "Microsoft.OSTCExtensions",
        "type": "CustomScriptForLinux",
        "typeHandlerVersion": "1.4",
        "settings": {
          "fileUris": [
            "url-of-script"
          ],
          "env": {
            "VM1NAME":  "[variables('vm1Name')]"
          },
          "commandToExecute": "sh setup-script.sh"
        }
      }
    }
```

I know I can pass those variables by putting them before the command, but this looks much more elegant to me.

**Comment by keithlemon** [comment]
I am also experiencing issues gaining access to environment variables like $HOME in scripts that are running through subprocess.Popen.  Does anyone have a workaround to address this.

**Comment by boumenot** [comment]
There has been no activity on this issue since January, so I'm closing it.  Please reopen as necessary.

If you want to share variables between processes my recommendation is store them in a file.  Environment variables will not propagate to the parent, so new children can use them.

**Comment by vadmeste** [comment]
:+1:
