### ISSUE TITLE
Can't encrypt data disk on RHEL 6 VM

### ISSUE THREAD

**Issue by AidarKh** [Azure/azure-linux-extensions#642]
According this article https://docs.microsoft.com/en-us/azure/security/azure-security-disk-encryption-faq#bkmk_LinuxOSSupport RHEL 6 image from Azure Gallery supports Data disk encryption. I have deployed new VM from RHEL 6.9 Azure Gallery image and tried to encrypt the data disk according this article https://docs.microsoft.com/en-us/azure/security/azure-security-disk-encryption-linux.
az vm encryption enable command has failed wit this error.

```
VM has reported a failure when processing extension 'AzureDiskEncryptionForLinux'. Error message: "Failed to encrypt data volumes with error: zero length field name in format, stack trace: Traceback (most recent call last):
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.15/main/handle.py", line 1534, in daemon_encrypt
    os_item_to_stamp=os_item_to_stamp):
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.15/main/handle.py", line 1722, in daemon_encrypt_data_volumes
    os_item_to_stamp=os_item_to_stamp)
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.15/main/handle.py", line 1371, in enable_encryption_all_in_place
    encryption_config=encryption_config)
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.15/main/handle.py", line 196, in stamp_disks_with_settings
    settings.post_to_wireserver(data)
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.15/main/EncryptionSettingsUtil.py", line 236, in post_to_wireserver
    self.write_settings_file(data)
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.15/main/EncryptionSettingsUtil.py", line 229, in write_settings_file
    with open(self.get_settings_file_path(), 'w', 0) as outfile:
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.15/main/EncryptionSettingsUtil.py", line 82, in get_settings_file_path
    return CommonVariables.encryption_key_mount_point + '/' + self.get_settings_file_name()
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.15/main/EncryptionSettingsUtil.py", line 87, in get_settings_file_name
    return CommonVariables.encryption_settings_file_name_pattern.format(padded_index)
ValueError: zero length field name in format
".

```

**Comment by johanburati** [comment]
**Centos 6.9** comes with **python 2.6.6**
It looks like the single pass encryption method requires **python 2.7.5**  (non-numbered format fields)

Please try encrypting the VM using the old method, the one with the  **-AadClientID**/**-AadClientSecret** options
https://docs.microsoft.com/en-us/azure/security/azure-security-disk-encryption-linux-aad
