### ISSUE TITLE
AzureDiskEncryptionForLinux: Did not find BEK volume to store passphrase in

### ISSUE THREAD

**Issue by johanburati** [Azure/azure-linux-extensions#657]
A customer is having the follow error on a marketplace Ubuntu VM (**Canonical:UbuntuServer:16.04-LTS:latest**) with a data disk.

**AzureDiskEncryptionForLinux**  version is **1.1.0.17**

```
2018/10/03 20:49:52 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 13940: [Error] Failed to enable the extension with error: Did not find BEK volume to store passphrase in, stack trace
: Traceback (most recent call last):
2018/10/03 20:49:52   File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.17/main/handle.py", line 695, in enable_encryption
2018/10/03 20:49:52     bek_util.store_bek_passphrase(encryption_config, extension_parameter.passphrase)
2018/10/03 20:49:52   File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.17/main/BekUtil.py", line 76, in store_bek_passphrase
2018/10/03 20:49:52     raise Exception("Did not find BEK volume to store passphrase in")
2018/10/03 20:49:52 Exception: Did not find BEK volume to store passphrase in
2018/10/03 20:49:52
2018/10/03 20:49:52 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: [StatusReport (0)] op: EnableEncryption
2018/10/03 20:49:52 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: [StatusReport (0)] status: error
2018/10/03 20:49:52 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: [StatusReport (0)] code: 100
2018/10/03 20:49:52 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: [StatusReport (0)] msg: Failed to enable the extension with error: Did not find BEK volume to store passphrase in, st
ack trace: Traceback (most recent call last):
2018/10/03 20:49:52   File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.17/main/handle.py", line 695, in enable_encryption
2018/10/03 20:49:52     bek_util.store_bek_passphrase(encryption_config, extension_parameter.passphrase)
2018/10/03 20:49:52   File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.17/main/BekUtil.py", line 76, in store_bek_passphrase
2018/10/03 20:49:52     raise Exception("Did not find BEK volume to store passphrase in")
2018/10/03 20:49:52 Exception: Did not find BEK volume to store passphrase in
2018/10/03 20:49:52
```

**Comment by ejarvi** [comment]
This error means that the volume storing the key used to unlock the disk is missing.  This volume is attached to the VM by the host when it recognizes the VM as being enabled for disk encryption.   

There are different reasons why the host might fail to retrieve the key from key vault and/or attach a key volume to the VM.  These could include:  invalid key vault input being provided, a mismatch between the region of the key vault and the VM, or the key vault being deleted at some point in the process.  Without more detail on the steps that were taken prior to this error, it is difficult to debug further.    

Examples on how to set up key vault prerequisites properly prior to enabling encryption are available for Powershell ([here](https://github.com/Azure/azure-powershell/blob/master/src/ResourceManager/Compute/Commands.Compute/Extension/AzureDiskEncryption/Scripts/AzureDiskEncryptionPreRequisiteSetup.ps1)) and CLI ([here](https://github.com/Azure-Samples/azure-cli-samples/tree/master/disk-encryption/prereq)). 

To diagnose why this volume is missing, further information about the steps taken leading up to this error are needed.

**Comment by MRMTI** [comment]
Hi Guys,
Looking at this threat it seems logical to add some comments here. I was having similar issues except that mine is not able to encrypt the disks due to BEK Volume not being available during the "set-azurermvmdiskencryptionextension" command failing the transaction becuase it doesnt have the volume. See attachment of my error message. Any ideas would be most welcome as i'm getting the idea not many have encounter this problem before encrypting the disks.. i can find only threats about the BEK Volume missing after the disks are encrypted.
Thanks,
Michael

[DiskEncryptionErrorBekVolumeMissing.txt](https://github.com/Azure/azure-linux-extensions/files/2962344/DiskEncryptionErrorBekVolumeMissing.txt)
