### ISSUE TITLE
AzureDiskEncryptionForLinux:  Encryption failed for name:sdd1 type:part fstype:xfs mountpoint:/datadisk

### ISSUE THREAD

**Issue by johanburati** [Azure/azure-linux-extensions#658]
I tried deploying two marketplace Ubuntu VMs (Canonical:UbuntuServer:16.04-LTS:latest) with a data disk.

And tried to encrypt the data disk with the following command and got the same error for both VMs:
```
$  az vm encryption enable --resource-group vm01 --name vm01 --disk-encryption-keyvault vault8167 --key-encryption-key key --volume-type data --output table
VM has reported a failure when processing extension 'AzureDiskEncryptionForLinux'. Error message: "Failed to encrypt data volumes with error: Encryption failed for name:sdd1 type:part fstype:xfs mountpoint:/datadisk label: model: size:268434407424 majmin:8:49 device_id:f8b3781b-1e82-4818-a1c3-63d806ec15bb, stack trace: Traceback (most recent call last):
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.17/main/handle.py", line 1534, in daemon_encrypt
    os_items_to_stamp=os_items_to_stamp):
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.17/main/handle.py", line 1755, in daemon_encrypt_data_volumes
    raise Exception(message)
Exception: Encryption failed for name:sdd1 type:part fstype:xfs mountpoint:/datadisk label: model: size:268434407424 majmin:8:49 device_id:f8b3781b-1e82-4818-a1c3-63d806ec15bb
```
AzureDiskEncryptionForLinux  version is 1.1.0.17

**extension.log**:
```
2018/10/04 05:53:53 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: [StatusReport (0)] msg: Encrypting 1 data volumes
2018/10/04 05:53:53 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 19688: [Info] Data volume /datadisk is mounted from /dev/sdd1
2018/10/04 05:53:53 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: [StatusReport (0)] substatus: {"os": "NotEncrypted", "data": "EncryptionInProgress"}
2018/10/04 05:53:53 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 19688: [Info] Executing: /bin/umount /datadisk
2018/10/04 05:53:53 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 19688: [Info] encrypting: name:sdd1 type:part fstype:xfs mountpoint:/datadisk label: model: size:268434407424 majmin:8:49 device_id:f8b3781b-1e82-4818-a1c3-63d806ec15bb
2018/10/04 05:53:53 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 19688: [Warning] For VMSS we only do inplace headers
2018/10/04 05:53:53 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 19688: [Info] encrypt_inplace_without_seperate_header_file
2018/10/04 05:53:53 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 19688: [Info] encrypting device item: /dev/sdd1
2018/10/04 05:53:53 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 19688: [Info] the current phase is BackupHeader
2018/10/04 05:53:53 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 19688: [Warning] we only support ext file systems for centos 6.5/6.6/6.7 and redhat 6.7
2018/10/04 05:53:53 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 19688: [Info] archive the config file: /var/lib/azure_disk_encryption_config/azure_crypt_ongoing_item.ini
2018/10/04 05:53:53 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 19688: [Error] Failed to encrypt data volumes with error: Encryption failed for name:sdd1 type:part fstype:xfs mountpoint:/datadisk label: model: size:268434407424 majmin:8:49 device_id:f8b3781b-1e82-4818-a1c3-63d806ec15bb, stack trace: Traceback (most recent call last):
2018/10/04 05:53:53   File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.17/main/handle.py", line 1534, in daemon_encrypt
2018/10/04 05:53:53     os_items_to_stamp=os_items_to_stamp):
2018/10/04 05:53:53   File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.17/main/handle.py", line 1755, in daemon_encrypt_data_volumes
2018/10/04 05:53:53     raise Exception(message)
2018/10/04 05:53:53 Exception: Encryption failed for name:sdd1 type:part fstype:xfs mountpoint:/datadisk label: model: size:268434407424 majmin:8:49 device_id:f8b3781b-1e82-4818-a1c3-63d806ec15bb
2018/10/04 05:53:53
2018/10/04 05:53:53 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: [StatusReport (0)] op: EnableEncryptionDataVolumes
2018/10/04 05:53:53 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: [StatusReport (0)] status: error
2018/10/04 05:53:53 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: [StatusReport (0)] code: 19
2018/10/04 05:53:53 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: [StatusReport (0)] msg: Failed to encrypt data volumes with error: Encryption failed for name:sdd1 type:part fstype:xfs mountpoint:/datadisk label: model: size:268434407424 majmin:8:49 device_id:f8b3781b-1e82-4818-a1c3-63d806ec15bb, stack trace: Traceback (most recent call last):
2018/10/04 05:53:53   File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.17/main/handle.py", line 1534, in daemon_encrypt
2018/10/04 05:53:53     os_items_to_stamp=os_items_to_stamp):
2018/10/04 05:53:53   File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.17/main/handle.py", line 1755, in daemon_encrypt_data_volumes
2018/10/04 05:53:53     raise Exception(message)
2018/10/04 05:53:53 Exception: Encryption failed for name:sdd1 type:part fstype:xfs mountpoint:/datadisk label: model: size:268434407424 majmin:8:49 device_id:f8b3781b-1e82-4818-a1c3-63d806ec15bb
2018/10/04 05:53:53
2018/10/04 05:53:53 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: [StatusReport (0)] substatus: {"os": "NotEncrypted", "data": "NotMounted"}
2018/10/04 05:53:53 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 19688: [Info] exiting daemon
```

After the encryption failed, I mounted back the data disk:
```
# cat /etc/fstab
UUID=fc9a41df-6d71-4f4f-a487-e5999bd67182       /        ext4   defaults,discard        0 0
/dev/disk/cloud/azure_resource-part1    /mnt    auto    defaults,nofail,x-systemd.requires=cloud-init.service,comment=cloudconfig       0       2
UUID=d1be93dc-d5bb-4ecf-b5ed-f58fc45574cb /datadisk                     xfs     defaults         1 0
# mount -a
# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sdd      8:48   0  250G  0 disk
└─sdd1   8:49   0  250G  0 part /datadisk
sdb      8:16   0    7G  0 disk
└─sdb1   8:17   0    7G  0 part /mnt
sr0     11:0    1 1024M  0 rom
sdc      8:32   0   48M  0 disk
└─sdc1   8:33   0   47M  0 part /mnt/azure_bek_disk
sda      8:0    0   30G  0 disk
└─sda1   8:1    0   30G  0 part /
```

**Comment by ejarvi** [comment]
@vermashi can you take a look at this and add any thoughts?  There appears to be an issue related to stamping encryption settings for an xfs data disk on Ubuntu.

**Comment by quartoquar** [comment]
Hi,

Initially I got the same error and I was exactly in the same step: with /mnt/azure_bek_disk mounted and /dev/sdd1 unmounted and error:

PS Azure:\> az vm encryption enable --resource-group "RG_NAME" --name "VM-NAME" --disk-encryption-keyvault "KeyVaultName" --volume-type All --output table

Deployment failed. Correlation ID: a4084350-1d6c-46a3-9af8-bcba43b7xxxx. VM has reported a failure when processing extension 'AzureDiskEncryptionForLinux'. Error message: "Failed to encrypt data volumes with error: Encryption failed forname:sdd1 type:part fstype:xfs mountpoint:/data label: model: size:107373133824 majmin:8:49 device_id:f8b3781b-xxxx-4818-a1c3-63d806ecxxxx, stack trace: Traceback (most recent call last):
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.20/main/handle.py", line 1541, in daemon_encrypt
    os_items_to_stamp=os_items_to_stamp):
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.20/main/handle.py", line 1763, in daemon_encrypt_data_volumes
    raise Exception(message)
Exception: Encryption failed for name:sdd1 type:part fstype:xfs mountpoint:/data label: model: size:107373133824 majmin:8:49 device_id:f8b3781b-xxxx-4818-a1c3-63d806ecxxxx

This happened because I lacked the "--key-encryption-key" option (which does not appear in Microsoft's documentation). After adding it, I was able to encrypt both disks at the same time correctly.

PS Azure:\> az vm encryption enable --resource-group "RG_NAME" --name "VM-NAME" --disk-encryption-keyvault "KeyVaultName" --key-encryption-key "KeyName" --volume-type All --output table

Have you enabled the KeyVault option to use encryption (Key Vault > Access policies > Click to show advanced access policies)? Verify with:

PS Azure:\> Get-AzureRmKeyVault -VaultName "KeyVaultName" -ResourceGroupName "RG_NAME"
[...]
Enabled For Deployment?          : True
Enabled For Template Deployment? : False
Enabled For Disk Encryption?     : True
[...]

Also check that the keyvault firewall is open or correctly configured.

My environment:
Ubuntu 16.04 LST from Azure Marketplace
XFS Data disk mounted in /data
Size: Standard_D2s_v3 (2 vcpu / 8 ram)

I hope it'll be helpful.

**Comment by quartoquar** [comment]
Hello,

This is the answer I was given when I opened a ticket with Microsoft support:

_"I have reviewed the logs and found that your data disk is using XFS file system. We regret to inform you that currently XFS  feature is encountering the issue which is restricting the data disk to be encrypted.
Considering your OS disk as encrypted, please find the workaround below. This will help you to encrypt the data disk."_

With EXT4 everything went perfectly.

I have asked Microsoft to include this information in the documentation With EXT4 everything went perfectly.

I requested to Microsoft to include this information in the documentation because I lost many hours in this incident.
