### ISSUE TITLE
Traceback on SLES

### ISSUE THREAD

**Issue by rjschwei** [Azure/azure-linux-extensions#672]
When trying to encrypt a SLES instance the following traceback is generated:

VM has reported a failure when processing extension 'AzureDiskEncryptionForLinux'. Error message: "Failed to enable the extension with error: 'NoneType' object has no attribute 'getheader', stack trace: Traceback (most recent call last):
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999322/main/handle.py", line 691, in enable_encryption
    DiskEncryptionKeyFileName=extension_parameter.DiskEncryptionKeyFileName)
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-0.1.0.999322/main/KeyVaultUtil.py", line 63, in create_kek_secret
    bearerHeader = result.getheader("www-authenticate")
AttributeError: 'NoneType' object has no attribute 'getheader'

**Comment by szarkos** [comment]
Was this on SLES12-SP3 or SLES15?

**Comment by szarkos** [comment]
Hi Robert,

It seems the VM Encryption extension lacks Python3 support, which may explain this error.  I believe this support is on the backlog.

Thanks,
Steve

**Comment by rjschwei** [comment]
The traceback was from SLES 15, but SLES 12 is not working either, different symptom.

We will help sort this out, I have asked one of my team members, @edlane to look at this

**Comment by edlane** [comment]
I need additional info to recreate this issue.
I got encryption on SLES12 to work with this "az" CLI sequence...
```
ed-sle12sp3byos:/mnt/resource # az keyvault create --name "edlanevault" --resource-group "ed_lane"
```
... then I followed the directions for allowing key vault access for disk encryption described here: https://docs.microsoft.com/en-us/azure/security/azure-security-disk-encryption-prerequisites

... then I enabled encryption on a data disk as follows:
```
ed-sle12sp3byos:/mnt/resource #az vm encryption enable --resource-group ed_lane --name ed-sle12sp3byos --disk-encryption-keyvault edlanevault --volume-type Data
ed-sle12sp3byos:/mnt/resource #az vm encryption show --name ed-sle12sp3byos --resource-group ed_lane
{
  "disks": [
    {
      "encryptionSettings": [
        {
          "diskEncryptionKey": null,
          "enabled": false,
          "keyEncryptionKey": null
        }
      ],
      "name": "ed-sle12sp3byos_OsDisk_1_8c65f1e6526b41109e3f0d73c609b57f",
      "statuses": [
        {
          "code": "EncryptionState/notEncrypted",
          "displayStatus": "Disk is not encrypted",
          "level": "Info",
          "message": null,
          "time": null
        }
      ]
    },
    {
      "encryptionSettings": [
        {
          "diskEncryptionKey": {
            "secretUrl": "https://edlanevault.vault.azure.net/secrets/6a951275-c935-49cb-bdd3-11ad372322f8/60474468e6d3493d9b37f6fde5843cb7",
            "sourceVault": {
              "id": "/subscriptions/ce73a2b0-d2e7-4ff6-b987-b32d6908de4e/resourceGroups/ed_lane/providers/Microsoft.KeyVault/vaults/edlanevault"
            }
          },
          "enabled": true,
          "keyEncryptionKey": null
        }
      ],
      "name": "ed-sle12sp3_OsDisk_1_f9a8641560b945aa86a75185e5257f19",
      "statuses": [
        {
          "code": "EncryptionState/encrypted",
          "displayStatus": "Encryption is enabled on disk",
          "level": "Info",
          "message": null,
          "time": null
        }
      ]
    }
  ],
  "status": [
    {
      "code": "ProvisioningState/succeeded",
      "displayStatus": "Provisioning succeeded",
      "level": "Info",
      "message": "Encrypting data volume 2/2: 78%",
      "time": null
    }
  ],
  "substatus": [
    {
      "code": "ComponentStatus/Microsoft.Azure.Security.AzureDiskEncryptionForLinux/succeeded",
      "displayStatus": "Provisioning succeeded",
      "level": "Info",
      "message": "{\"os\": \"NotEncrypted\", \"data\": \"NotMounted\"}",
      "time": null
    }
  ]
}
```

**Comment by rjschwei** [comment]
Provided info via e-mail

**Comment by edlane** [comment]
@szarkos ,
Apart from reverse engineering the RHEL and Ubuntu implementations from source code, is there any documentation on **waagent APIs** or a Linux Extension developer guide?
... or a human contact for these Linux extensions?
I have made some progress on SUSE encryption by reverse engineering but need some further clarification for completion.

**Comment by edlane** [comment]
@szarkos  -- never mind for now
I just discovered the "--debug" option to the az command which answers most of my questions
This should get me to the finish line

**Comment by edlane** [comment]
@szarkos 
I have prepared a PR to provide Root Volume Encryption support for SUSE 12 and 15.  In order to complete end-to-end testing without manual intervention and hacks, answers to the following questions are requested:

1. According to FAQ https://docs.microsoft.com/en-us/azure/security/azure-security-disk-encryption-faq#bkmk_LinuxOSSupport : 
SUSE currently only supports Data Disks and an error is generated when requesting OS-VOLUME encryption from Azure CLI.

- [ ] **How do you add SUSE 12&15 to list of supported Distros and prevent error messages from "az" command when OS-VOLUME encryption is requested?**

2. Currently for development, I  first load the existing SUSE  encryption code by specifying  DATA-VOLUME encryption (Apparently Linux Extension code is loaded on demand from some existing Azure repo). Following that operation I then "side-load" development code over the top of the existing code base for subsequent OS-VOLUME encryption operation.   If you attempt "side-loading" your development code without first forcing a download of the Linux Extension from Azure your "side-loaded" code is automatically deleted by some background agent (presumably this is done by waagent)

- [ ] **How is new Linux Extension code made available from this Azure repo?**  
- [ ] **How does a developer reconcile a Git repo version with the on-demand version which shows up on the VM instance -- eg. which git branch/label is equal to  /var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.22/ ?**
- [ ] **How can you accomplish a development workflow which does not require the "side-load" hackery described above?**

**Comment by aosthof** [comment]
@szarkos 
Steve, when can we expect the questions from Ed to be answered?

**Comment by vermashi** [comment]
Hi Ed,
ADE team member here. Thank you for putting in all this effort. Let me try to answer your questions:

1. The warning used to be in the Azure CLI repo. But the warning messages have been removed as of this commit: https://github.com/Azure/azure-cli/commit/e8da09b4771ee2d8134e3e9cd30314c2717f156b

2.1 Our team regularly pulls from this Repo and deploys Azure Disk Encryption extension updates. (about every 1-2 weeks).
2.2 There are two version of ADE, the old version with AAD credentials. This is pulled from the master branch. And there is the newer version (without AAD credential. AKA single-pass) which pulls from the 'ade-singlepass-master' branch
2.3 Internal ADE team members generally also use "side-loading" for quick manual testing. For end-to-end and automated testing we (team members) have ways to release beta/test versions of the extension. But the process of releasing it takes a while so we use it generally for pre-release testing of master/ ade-singlepass-master branches.

Can you point to the PR you have made, I can help steer it in the right direction and speed you along.

**Comment by aosthof** [comment]
@vermashi Thanks for your detailed answers.
@edlane Please provide the link to the PR you've prepared, thanks.

**Comment by edlane** [comment]
@aosthof PR has been submitted here:
https://github.com/Azure/azure-linux-extensions/pull/805
