### ISSUE TITLE
Azure.Diagnostics.LinuxDiagnostic "Failed to set up mdsd dependencies"

### ISSUE THREAD

**Issue by carct** [Azure/azure-linux-extensions#695]
i`m getting an error from:
TYPE Microsoft.Azure.Diagnostics.LinuxDiagnostic
VERSION 3.0.117

OS:
Ubuntu 16.04 (x86_64) | 16.04.201808140

Other extensions present related to this (successfully installed):

DependencyAgentLinux: VERSION 9.7.3.1475
OmsAgentForLinux: VERSION 1.8.9

Error message:
Failed to set up mdsd dependencies: omsagent setup failed 5 times. Last exit code=3, Output=setup_omsagent_for_lad(): fluentd out_mdsd plugin install failed. Output: /opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rubygems/safe_yaml (LoadError) from /opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require' from /opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems.rb:702:in `load_yaml' from /opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems/config_file.rb:340:in `load_file' from /opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems/config_file.rb:202:in `initialize' from /opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems/gem_runner.rb:75:in `new' from /opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems/gem_runner.rb:75:in `do_configuration' from /opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems/gem_runner.rb:40:in `run' from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.4.0/gems/fluentd-0.12.40/bin/fluent-gem:6:in `<top (required)>' from /opt/microsoft/omsagent/ruby/bin/fluent-gem:23:in `load' from /opt/microsoft/omsagent/ruby/bin/fluent-gem:23:in `<main>'
HANDLER STATUSReady
HANDLER STATUS LEVELInfo

i could find a similar issue but seems to be closed...
https://github.com/Azure/azure-linux-extensions/issues/488#issuecomment-439878427

**Comment by therealpstutz** [comment]
I am also having the same issue.  Was able to reproduce on Centos  6.10, Ubuntu 16.04.5 LTS and Ubuntu 18.04.1 LTS.

**Comment by shpimpal** [comment]
This may happen if there is OMS agent already installed and then LAD is installed. As a workaround, please uninstall OMS agent --> install LAD --> install OMS agent if you need.

The fix is checked in here - https://github.com/Microsoft/OMS-Agent-for-Linux/commit/f962a8a33e5b9efda536ea0be4ab8ddf763646d7 and will be out with next release of OMS agent, thanks!

**Comment by sean-nixon** [comment]
I am still seeing this issue on Ubuntu 14.04.5 LTS running LinuxDiagnostic 3.0.119 and OMS 1.8.12. Has this fix been released yet?

**Comment by andrewatfornax** [comment]
I also still see this issue on RHEL 7.2.

**Comment by IanLin419** [comment]
I also still see this issue on RHEL 6.8.

**Comment by Rangi-th** [comment]
Yes the problem persists. RHEL 7.5

**Comment by mrevros** [comment]
Hi All,
OS:CentOS 7.6
I tried same steps but it is not working.

TYPEMicrosoft.Azure.Diagnostics.LinuxDiagnostic
VERSION3.0.119
STATUSProvisioning failed
STATUS LEVELError
STATUS MESSAGEFailed to set up mdsd dependencies: omsagent setup failed 5 times. Last exit code=3, Output=setup_omsagent_for_lad(): fluentd out_mdsd plugin install failed. Output: /opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rubygems/safe_yaml (LoadError) from /opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require' from /opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems.rb:702:in `load_yaml' from /opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems/config_file.rb:340:in `load_file' from /opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems/config_file.rb:202:in `initialize' from /opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems/gem_runner.rb:75:in `new' from /opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems/gem_runner.rb:75:in `do_configuration' from /opt/microsoft/omsagent/ruby/lib/ruby/2.4.0/rubygems/gem_runner.rb:40:in `run' from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.4.0/gems/fluentd-0.12.40/bin/fluent-gem:6:in `<top (required)>' from /opt/microsoft/omsagent/ruby/bin/fluent-gem:23:in `load' from /opt/microsoft/omsagent/ruby/bin/fluent-gem:23:in `<main>'
HANDLER STATUSReady
HANDLER STATUS LEVELInfo

**Comment by yobyot** [comment]
Upgrading an Ubuntu 18.04 to LAD 3 produces this error for me.

**Comment by Rangi-th** [comment]
The problem seems to be fixed in latest OMS release: 1.9.1

I tested this on CentOS 7.5 and RHEL 7.2 (installing OMS agent first and then installing LAD)

**Comment by axelgMS** [comment]
possible mitigation - haven't tested

uninstall OMS agent, install LAD, then install OMS agent if required (ensure latest version OMS v1.9+ is attempted, since it includes fix for LAD install conflicts).

**Comment by johanburati** [comment]
Still seeing this error with **OmsAgentForLinux v1.12.25** and **LinuxDiagnostic v3.0.127**:


```
ERROR:CalledProcessError. Error Code is 1
ERROR:CalledProcessError. Command string was /opt/microsoft/omsagent/bin/service_control restart LAD
ERROR:CalledProcessError. Command result was
[Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.127] Return 1:
ERROR:[Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.127] Failed to set up mdsd dependencies: setup_omsagent(): Failed at restarting omsagent (fluentd). Exit code=1, Output=control_omsagent(restart) failed. Output:
[Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.127] Enable,error,1,Failed to set up mdsd dependencies: setup_omsagent(): Failed at restarting omsagent (fluentd). Exit code=1, Output=control_omsagent(restart) failed. Output:
[Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.127] Enable,error,-1,Enabled failed
```

**Comment by knlp** [comment]
It's almost Septembed and I'm still getting this.
```
2020/08/28 11:26:32 [Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.129] RunCmd dpkg -i lad-mdsd-*.deb
2020/08/28 11:26:32 ERROR:CalledProcessError.  Error Code is 2
2020/08/28 11:26:32 ERROR:CalledProcessError.  Command string was dpkg -i lad-mdsd-*.deb
2020/08/28 11:26:32 ERROR:CalledProcessError.  Command result was dpkg: error: dpkg frontend is locked by another process
2020/08/28 11:26:32 [Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.129] Return 2:dpkg: error: dpkg frontend is locked by another process
2020/08/28 11:26:32
2020/08/28 11:26:32 ERROR:[Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.129] Failed to set up mdsd dependencies: lad-mdsd pkg install failed. Exit code=2, Output=dpkg: error: dpkg frontend is locked by another process
2020/08/28 11:26:32 ERROR:
2020/08/28 11:26:32 [Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.129] Install,error,1,Failed to set up mdsd dependencies: lad-mdsd pkg install failed. Exit code=2, Output=dpkg: error: dpkg frontend is locked by another process
2020/08/28 11:26:32
2020/08/28 11:26:32 [Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.129] Install,error,-1,Install failed
```
