### ISSUE TITLE
Unable to initiate Azure Backup on SLE 15

### ISSUE THREAD

**Issue by dops0** [Azure/azure-linux-extensions#758]
We are having problems initiating a backup of our VM running SLE 15. 

The error message we get on Azure portal is **ExtensionSnapshotFailedNoNetwork**
We've set NSG rules allowing outbound access to Azure storage but still end up with this error. Logs on the VM itself give some information, but don't know if that helps pinpoint the problem.

```
waagent --version
WALinuxAgent-2.2.36 running on sles 15
Python: 3.6.5
Goal state agent: 2.2.37
```

From 
/var/log/azure/Microsoft.Azure.RecoveryServices.VMSnapshotLinux/extension.log

```
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]Failed to construct ConfigurationProvider, which may due to the old wala code.
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]GetBlobProperties: Failed to get blob properties with error: __init__() takes exactly 2 arguments (1 given), stack trace: Traceback (most recent call last):
2019/03/01 17:58:35   File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9147.0/main/blobwriter.py", line 207, in GetBlobProperties
2019/03/01 17:58:35     http_util = HttpUtil(self.hutil)
2019/03/01 17:58:35   File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9147.0/main/HttpUtil.py", line 43, in __init__
2019/03/01 17:58:35     Config = waagent.ConfigurationProvider()
2019/03/01 17:58:35 TypeError: __init__() takes exactly 2 arguments (1 given)
2019/03/01 17:58:35 
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]GetBlobProperties: retry times is 3
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]Failed to construct ConfigurationProvider, which may due to the old wala code.
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]GetBlobProperties: Failed to get blob properties with error: __init__() takes exactly 2 arguments (1 given), stack trace: Traceback (most recent call last):
2019/03/01 17:58:35   File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9147.0/main/blobwriter.py", line 207, in GetBlobProperties
2019/03/01 17:58:35     http_util = HttpUtil(self.hutil)
2019/03/01 17:58:35   File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9147.0/main/HttpUtil.py", line 43, in __init__
2019/03/01 17:58:35     Config = waagent.ConfigurationProvider()
2019/03/01 17:58:35 TypeError: __init__() takes exactly 2 arguments (1 given)
2019/03/01 17:58:35 
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]GetBlobProperties: retry times is 2
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]Failed to construct ConfigurationProvider, which may due to the old wala code.
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]GetBlobProperties: Failed to get blob properties with error: __init__() takes exactly 2 arguments (1 given), stack trace: Traceback (most recent call last):
2019/03/01 17:58:35   File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9147.0/main/blobwriter.py", line 207, in GetBlobProperties
2019/03/01 17:58:35     http_util = HttpUtil(self.hutil)
2019/03/01 17:58:35   File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9147.0/main/HttpUtil.py", line 43, in __init__
2019/03/01 17:58:35     Config = waagent.ConfigurationProvider()
2019/03/01 17:58:35 TypeError: __init__() takes exactly 2 arguments (1 given)
2019/03/01 17:58:35 
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]GetBlobProperties: retry times is 1
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]GetBlobType: Blob-Type :BlockBlob
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]Failed to construct ConfigurationProvider, which may due to the old wala code.
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]Failed to committing the log with error: __init__() takes exactly 2 arguments (1 given), stack trace: Traceback (most recent call last):
2019/03/01 17:58:35   File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9147.0/main/blobwriter.py", line 67, in WriteBlockBlob
2019/03/01 17:58:35     http_util = HttpUtil(self.hutil)
2019/03/01 17:58:35   File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9147.0/main/HttpUtil.py", line 43, in __init__
2019/03/01 17:58:35     Config = waagent.ConfigurationProvider()
2019/03/01 17:58:35 TypeError: __init__() takes exactly 2 arguments (1 given)
2019/03/01 17:58:35 
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]retry times is 3
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]Failed to construct ConfigurationProvider, which may due to the old wala code.
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]Failed to committing the log with error: __init__() takes exactly 2 arguments (1 given), stack trace: Traceback (most recent call last):
2019/03/01 17:58:35   File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9147.0/main/blobwriter.py", line 67, in WriteBlockBlob
2019/03/01 17:58:35     http_util = HttpUtil(self.hutil)
2019/03/01 17:58:35   File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9147.0/main/HttpUtil.py", line 43, in __init__
2019/03/01 17:58:35     Config = waagent.ConfigurationProvider()
2019/03/01 17:58:35 TypeError: __init__() takes exactly 2 arguments (1 given)
2019/03/01 17:58:35 
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]retry times is 2
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]Failed to construct ConfigurationProvider, which may due to the old wala code.
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]Failed to committing the log with error: __init__() takes exactly 2 arguments (1 given), stack trace: Traceback (most recent call last):
2019/03/01 17:58:35   File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9147.0/main/blobwriter.py", line 67, in WriteBlockBlob
2019/03/01 17:58:35     http_util = HttpUtil(self.hutil)
2019/03/01 17:58:35   File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9147.0/main/HttpUtil.py", line 43, in __init__
2019/03/01 17:58:35     Config = waagent.ConfigurationProvider()
2019/03/01 17:58:35 TypeError: __init__() takes exactly 2 arguments (1 given)
2019/03/01 17:58:35 
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]retry times is 1

```

**Comment by vrdmr** [comment]
@soumyapattnaik Can you please take a look at this issue?

**Comment by EstebanLopezF** [comment]
Hello, is there any update regarding to this issue?
All the new SLES 15 (BYOL) marketplace VMs seems to be facing the same issue.

**Comment by dops0** [comment]
Hi,

Any update on this issue? Has it been fixed ?

Thanks.

/Dev

**Comment by aidancopps** [comment]
This problem seems to still be ongoing, encountered it on a newly provisioned SLES VM this week.

**Comment by JozoSlejko** [comment]
@soumyapattnaik Could we have an update on this issue?

**Comment by christiansetzer** [comment]
Over a year has passed by since this issue was reported. I am still encountering a similar error and cannot initiate backups on my images

> 2020/09/07 07:11:23   File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9167.0/main/Utils/HandlerUtil.py", line 406, in get_machine_id
2020/09/07 07:11:23     machine_id = mi.stored_identity()[1:-1]
2020/09/07 07:11:23 TypeError: 'NoneType' object has no attribute '__getitem__'
2020/09/07 07:11:23
2020/09/07 07:11:23 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]Unique Machine Id  :
2020/09/07 07:11:23 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]partition count : 0, total used size : 0, is storage space present : False, is size computation failed : False
2020/09/07 07:11:23 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]Failed to retrieve the unique machine id with error: 'NoneType' object has no attribute '__getitem__', stack trace: Traceback (most recent call last):
2020/09/07 07:11:23   File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9167.0/main/Utils/HandlerUtil.py", line 406, in get_machine_id
2020/09/07 07:11:23     machine_id = mi.stored_identity()[1:-1]
2020/09/07 07:11:23 TypeError: 'NoneType' object has no attribute '__getitem__'

The machine-id is generated on boot and also available under /etc/machine-id and /var/lib/dbus/machine-id.

I just wanted to know, if the original problem was solved, then I would open up a issue for this myself.

waagent --version
WALinuxAgent-2.2.45 running on sles 15.1
Python: 3.6.10
Goal state agent: 2.2.45
