### ISSUE TITLE
ADE: Error when enabling encryption

### ISSUE THREAD

**Issue by IMG-PRCSNG** [Azure/azure-linux-extensions#769]
I am trying to encrypt the OS disk of a linux VM. I have setup the keyvault and created a key encryption key, added firewall rules to allow request from the subnet etc. This VM was created from an image, which was created from Ubuntu 16.04 gallery image.

This is the log from the `az vm encryption enable` command
```
VM has reported a failure when processing extension 'AzureDiskEncryptionForLinux'. Error message: "Failed to encrypt OS volume with error: encryption settings update request was not accepted, stack trace: Traceback (most recent call last):
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.28/main/handle.py", line 1631, in daemon_encrypt
    stamp_disks_with_settings(os_items_to_stamp, encryption_config)
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.28/main/handle.py", line 197, in stamp_disks_with_settings
    settings.post_to_wireserver(data)
  File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.28/main/EncryptionSettingsUtil.py", line 251, in post_to_wireserver
    raise e
Exception: encryption settings update request was not accepted
, machine state: uninitialized".
```

I get the following log from the `/var/log/azure/Microsoft.Azure.Security.AzureDiskEncryptionForLinux/extension.log` file when I try to encrypt a VM. Logs are shortened to include only the error section. I can upload the full logs if required. I also tried printing the wireserver endpoint and the argument. (Prefixed by $$$$ in the following)

```
2019/03/18 04:05:13 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 1631: [Info] Creating encryption settings object
2019/03/18 04:05:13 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 1631: [Info] /var/lib/azure_disk_encryption_config/azure_crypt_mount does not exist
2019/03/18 04:05:13 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 1631: [Info] device items which will be used to find vhds to stamp: set(['/dev/sda1'])
2019/03/18 04:05:13 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 1631: [Info] getting blk info for: /dev/sda
2019/03/18 04:05:13 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 1631: [Info] Executing: lvs --noheadings --nameprefixes --unquoted -o lv_name,vg_name,lv_kernel_major,lv_kernel_minor
2019/03/18 04:05:13 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 1631: [Info] encryption settings counter file not found, returning index value 0
2019/03/18 04:05:15 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 1631: [Info] 500 [('date', 'Mon, 18 Mar 2019 04:05:14 GMT'), ('content-length', '1208'), ('content-type', 'text/html'), ('server', 'Microsoft-IIS/10.0')]
2019/03/18 04:05:15 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 1631: [Info] result_content is <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">^M
2019/03/18 04:05:15 <html xmlns="http://www.w3.org/1999/xhtml">^M
2019/03/18 04:05:15 <head>^M
2019/03/18 04:05:15 <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>^M
2019/03/18 04:05:15 <title>500 - Internal server error.</title>^M
2019/03/18 04:05:15 <style type="text/css">
2019/03/18 04:17:39 <!--
2019/03/18 04:17:39 body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
2019/03/18 04:17:39 fieldset{padding:0 15px 10px 15px;}
2019/03/18 04:17:39 h1{font-size:2.4em;margin:0;color:#FFF;}
2019/03/18 04:17:39 h2{font-size:1.7em;margin:0;color:#CC0000;}
2019/03/18 04:17:39 h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
2019/03/18 04:17:39 #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
2019/03/18 04:17:39 background-color:#555555;}
2019/03/18 04:17:39 #content{margin:0 0 0 2%;position:relative;}
2019/03/18 04:17:39 .content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
2019/03/18 04:17:39 -->
2019/03/18 04:17:39 </style>
2019/03/18 04:17:39 </head>
2019/03/18 04:17:39 <body>
2019/03/18 04:17:39 <div id="header"><h1>Server Error</h1></div>
2019/03/18 04:17:39 <div id="content">
2019/03/18 04:17:39  <div class="content-container"><fieldset>
2019/03/18 04:17:39   <h2>500 - Internal server error.</h2>
2019/03/18 04:17:39   <h3>There is a problem with the resource you are looking for, and it cannot be displayed.</h3>
2019/03/18 04:17:39  </fieldset></div>
2019/03/18 04:17:39 </div>
2019/03/18 04:17:39 </body>
2019/03/18 04:17:39 </html>
2019/03/18 04:17:39

2019/03/18 04:17:39 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 5953: [Info] $$$$$ http://169.254.169.254:80/machine?comp=diskEncryptionData <?xml version="1.0"?>
2019/03/18 04:17:39     <DiskEncryptionData version="2.0">
2019/03/18 04:17:39         <DiskEncryptionSettingsFile>settings_03.json</DiskEncryptionSettingsFile>
2019/03/18 04:17:39     </DiskEncryptionData>
2019/03/18 04:17:39

2019/03/18 04:17:39 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 5953: [Info] Encountered exception while posting encryption settings to Wire Server (attempt #3):
2019/03/18 04:17:39 encryption settings update request was not accepted
2019/03/18 04:17:39 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 5953: [Error] Failed to encrypt OS volume with error: encryption settings update request was not accepted, stack trace: Traceback (most recent call last):
2019/03/18 04:17:39   File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.28/main/handle.py", line 1631, in daemon_encrypt
2019/03/18 04:17:39     stamp_disks_with_settings(os_items_to_stamp, encryption_config)
2019/03/18 04:17:39   File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.28/main/handle.py", line 197, in stamp_disks_with_settings
2019/03/18 04:17:39     settings.post_to_wireserver(data)
2019/03/18 04:17:39   File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.28/main/EncryptionSettingsUtil.py", line 254, in post_to_wireserver
2019/03/18 04:17:39     raise e
2019/03/18 04:17:39 Exception: encryption settings update request was not accepted
2019/03/18 04:17:39 , machine state: uninitialized
2019/03/18 04:17:40 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: [StatusReport (1)] op: EnableEncryptionOSVolume
2019/03/18 04:17:40 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: [StatusReport (1)] status: error
2019/03/18 04:17:40 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: [StatusReport (1)] code: 19
2019/03/18 04:17:40 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: [StatusReport (1)] msg: Failed to encrypt OS volume with error: encryption settings update request was not accepted, stack trace: Traceback (most recent call last):
2019/03/18 04:17:40   File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.28/main/handle.py", line 1631, in daemon_encrypt
2019/03/18 04:17:40     stamp_disks_with_settings(os_items_to_stamp, encryption_config)
2019/03/18 04:17:40   File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.28/main/handle.py", line 197, in stamp_disks_with_settings
2019/03/18 04:17:40     settings.post_to_wireserver(data)
2019/03/18 04:17:40   File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.28/main/EncryptionSettingsUtil.py", line 254, in post_to_wireserver
2019/03/18 04:17:40     raise e
2019/03/18 04:17:40 Exception: encryption settings update request was not accepted
2019/03/18 04:17:40 , machine state: uninitialized
2019/03/18 04:17:40 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: [StatusReport (1)] substatus: {"os": "EncryptionInProgress", "data": "NotMounted"}
2019/03/18 04:17:40 [Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 5953: [Info] exiting daemon
```

**Comment by johanburati** [comment]
Usually this error indicates an issue with the key vault access policies.

Try the following:

Go to the **Key vault** in the Azure portal, click on **Access policies**, click on the **Click to show advanced access policies** link, make sure the **Enable access to Azure Disk Encryption for volume encryption** check box is checked, then try to encrypt the VM again.

**Comment by IMG-PRCSNG** [comment]
I have that option enabled in the Access Policies.

Funnily, I created another VM and I was able to encrypt that with the same steps. Except that it was Premium SSD. The one which failed had Standard SSD.

I do not have a reliable way of reproducing the issue or where to look for further info which might help. Any pointers on that?

**Comment by johanburati** [comment]
If you still have a VM that is having that issue, the best would be to open a support case.

**Comment by IMG-PRCSNG** [comment]
I don't have the VM at the moment. But if I end up with the same problem again, I will raise a support request.

Since the logs contain a line saying "500 Internal Server Error", I assumed I was either doing some mistake while configuring it or there is a bug and putting it here might help.

I will close this for now. We can reopen it if I or someone else can reliably reproduce it.

**Comment by 1lomeno3** [comment]
Hi, I can easily reproduce the issue with one difference - I am trying to encrypt data disks with lvm volumes.

**Comment by tpag26** [comment]
I am experiencing the same issue

**Comment by johtull** [comment]
I'm getting the same issue with this setup:
Ubuntu 18.04, D2s_v3, Premium SSD

My key vault also has the proper access policies.

**Comment by pradeepvishwakarma** [comment]
Does that issue resolved ?

**Comment by c0nquest999** [comment]
I also get this error, when rotating keys.
In my case there is a counter file on /mnt/azure_bek_disk/ . I believe a number is read from this file and a setting file created, which in turn is posted to the wireserver as data (which generates the 500 error). 
When this error occurs the file is corrupted with a blank line above the correct number.  A reboot of the server fixes the issue and the counter file is fixed. I think that a blank line (or carrage return \n" is incorrectly written to the file.

**Comment by azsec** [comment]
You need to verify if the information you supply is correct. All info like Key Vault resource Id, Algorithm, Kek Key vault resource id or so on are encoded to initialize a request body called diskEncryptionData to be sent to Azure Metadata Instance service at **169.254.169.254**

I wrote this article to explain more on what is run behind the scene on windows
https://azsec.azurewebsites.net/2019/12/28/azure-disk-encryption-for-windows-vm/ , and bonus an Azure ARM template to deploy with zero stress.

For Linux it should be the same there is somewhere you would see a Python script to do the job.
