### ISSUE TITLE
AzureDiskEncryptionForLinux Fails with python error

### ISSUE THREAD

**Issue by davidlbyrne** [Azure/azure-linux-extensions#785]
We are trying to encrypt our disk and we keep getting this issue. 

Ubuntu 16.04.6 LTS

[Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 4468: [Error] Failed to update encryption settings with error: coercing to Unicode: need string or buffer, NoneType found, stack trace: Traceback (most recent call last):
2019/04/15 19:40:37   File "main/handle.py", line 313, in update_encryption_settings
2019/04/15 19:40:37     shutil.copy(existing_passphrase_file, encryption_environment.bek_backup_path)
2019/04/15 19:40:37   File "/usr/lib/python2.7/shutil.py", line 119, in copy
2019/04/15 19:40:37     copyfile(src, dst)
2019/04/15 19:40:37   File "/usr/lib/python2.7/shutil.py", line 68, in copyfile
2019/04/15 19:40:37     if _samefile(src, dst):
2019/04/15 19:40:37   File "/usr/lib/python2.7/shutil.py", line 58, in _samefile
2019/04/15 19:40:37     return os.path.samefile(src, dst)
2019/04/15 19:40:37   File "/usr/lib/python2.7/posixpath.py", line 155, in samefile
2019/04/15 19:40:37     s1 = os.stat(f1)
2019/04/15 19:40:37 TypeError: coercing to Unicode: need string

**Comment by mariusstrom** [comment]
+1
Ubuntu 18.04.2 LTS
Fails under azure-cli 2.0.67, PowerShell, and the Resource Manager quickstart template.
