### ISSUE TITLE
ADE: Add support for RHEL 8

### ISSUE THREAD

**Issue by johanburati** [Azure/azure-linux-extensions#809]
I have set up RHEL 8.0 with python2 since python3 is not supported (https://github.com/MicrosoftDocs/azure-docs/issues/31857)

```
# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.0 (Ootpa)
# python --version
Python 2.7.15
```

Getting an error when trying to encrypt the OS disk:
```
VM has reported a failure when processing extension 'AzureDiskEncryptionForLinux'. Error message: "Distro redhat 8.0 is not
...
[Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 1644: [Info] Executing: modprobe vfat
[Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 1644: [Info] PRECHECK: Fatal Exception thrown during precheck
[Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.0]: 1644: [Info] Traceback (most recent call last):
   File "main/handle.py", line 549, in enable
     cutil.precheck_for_fatal_failures(public_settings, encryption_status, DistroPatcher)
   File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.31/main/check_util.py", line 283, in precheck_for_fatal_failures
     self.is_supported_os(public_settings, DistroPatcher, encryption_status)
   File "/var/lib/waagent/Microsoft.Azure.Security.AzureDiskEncryptionForLinux-1.1.0.31/main/check_util.py", line 274, in is_supported_os
     raise Exception('Distro {0} {1} is not supported for OS encryption'.format(distro_name, distro_version))
 Exception: Distro redhat 8.0 is not supported for OS encryption
```

As for the Data disk, it gets encrypted, but no entry is added back to fstab after a reboot the encrypted volume does not get decrypted and mounted.

**Comment by AndyX-Net** [comment]
Hi @johanburati ,
 
 Exception: Distro redhat 8.0 is not supported for OS encryption
 
 Redhat 8.0 is not in the supported list, please try RHEL 8.2 or higher:
 https://docs.microsoft.com/en-us/azure/virtual-machines/linux/disk-encryption-overview#supported-operating-systems
