### ISSUE TITLE
VMBackup freebsd

### ISSUE THREAD

**Issue by gredondogc** [Azure/azure-linux-extensions#82]
When trying to launch the waagent on a freebsd machine I get this error:

/var/lib/waagent # Traceback (most recent call last):
  File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.3.0/main/handle.py", line 218, in <module>
    main()
  File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.3.0/main/handle.py", line 63, in main
    enable()
  File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.3.0/main/handle.py", line 73, in enable
    freezer = FsFreezer(backup_logger)
  File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.3.0/main/fsfreezer.py", line 47, in __init__
    self.mounts = Mounts(self.logger)
  File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.3.0/main/mounts.py", line 46, in __init__
    p = subprocess.Popen(['lsblk', '-l', '-n','-o','NAME,TYPE,FSTYPE,MOUNTPOINT'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/local/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

I figured the problem is that the 'lsblk' command does not exists on freebsd.

Is there an workaround?

The machine has the following status on the portal, extensions:
Microsoft.Azure.RecoveryServices.VMSnapshotLinux	1.0.3.0	Installing

**Comment by andyliuliming** [comment]
the vmbackup feature do not support FreeBSD yet.

**Comment by Tulkis** [comment]
Hi,

I want to ask if this has solved.
Any news doing freebsd backups five years after?

Regards.
