### ISSUE TITLE
[VMSnapshotLinux] Failed to retrieve the unique machine id

### ISSUE THREAD

**Issue by johanburati** [Azure/azure-linux-extensions#919]
## Issue

Keep seeing following error in *Microsoft.Azure.RecoveryServices.VMSnapshotLinux/extension.log*:
```
Failed to retrieve the unique machine id with error: 'NoneType' object has no attribute '__getitem__', stack trace: Traceback (most recent call last):
  File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9151.0/main/Utils/HandlerUtil.py", line 351, in get_machine_id
    machine_id = mi.stored_identity()[1:-1]
TypeError: 'NoneType' object has no attribute '__getitem__'

Unique Machine Id  :
sequence number is 0
setting file path is/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9151.0/config/0.settings
current seq no is 0
Config decoded correctly.
waagent new path is used
starting enable
Reading customSettings from public_settings
LUN list - [-1]
Enable,success,4,Transitioning state in extension
partition count : 0, total used size : 0, is storage space present : False, is size computation failed : False
Failed to retrieve the unique machine id with error: 'NoneType' object has no attribute '__getitem__', stack trace: Traceback (most recent call last):
  File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9151.0/main/Utils/HandlerUtil.py", line 351, in get_machine_id
    machine_id = mi.stored_identity()[1:-1]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

## Version
```
Azure Linux Agent Version:2.2.32.2
OS: redhat 7.6
Python: 2.7.5
Extension: VMSnapshotLinux-1.0.9151.0
```

**Comment by johanburati** [comment]
Still getting this error with _VMSnapshotLinux v1.0.9170.0_:
```
Failed to retrieve the unique machine id with error: 'NoneType' object is not subscriptable, stack trace: Traceback (most recent call last):
  File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9170.0/main/Utils/HandlerUtil.py", line 406, in get_machine_id
    machine_id = mi.stored_identity()[1:-1]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by ankitha-p** [comment]
This bug is fixed. https://github.com/Azure/azure-linux-extensions/pull/1649
