### ISSUE TITLE
[LinuxDiagnostic] Failed to launch mdsd with error: cannot concatenate 'str' and 'int' objects

### ISSUE THREAD

**Issue by johanburati** [Azure/azure-linux-extensions#948]
Seeing this error in *extension.log*:
```
Failed to launch mdsd with error: cannot concatenate 'str' and 'int' objects, traceback: Traceback (most recent call last): File "/var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.125/diagnostic.py", line 483, in start_mdsd omi_installed = restart_omi_if_crashed(omi_installed, mdsd) File "/var/lib/waagent/Microsoft.Azure.Diagnostics.LinuxDiagnostic-3.0.125/diagnostic.py", line 658, in restart_omi_if_crashed hutil.error("Re-installing the components failed with error code: " + dependencies_err + ", error message: " + dependencies_msg) TypeError: cannot concatenate 'str' and 'int' objects 
 ```

**Comment by johanburati** [comment]
Submitted a fix for this: PR https://github.com/Azure/azure-linux-extensions/pull/949
